
drop database BDJOIN
CREATE DATABASE BDJOIN
GO
USE BDJOIN
GO

CREATE TABLE CATEGORIA (
	CODCATEGORIA INT NOT NULL PRIMARY KEY, 
	NOMECATEGORIA VARCHAR(30)
)
GO
CREATE TABLE FORNECEDOR (CODFORNECEDOR INT IDENTITY NOT NULL PRIMARY KEY,
NOMEFORNECEDOR VARCHAR(50)
)
GO
CREATE TABLE PRODUTO (
	CODPRODUTO INT IDENTITY NOT NULL PRIMARY KEY, 
	NOMEPRODUTO VARCHAR(30), 
	CODCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA (CODCATEGORIA), 
	CODFORNECEDOR INT FOREIGN KEY REFERENCES FORNECEDOR (CODFORNECEDOR), 
	QUANTIDADE INT, 
	VALORUNITARIO DECIMAL(10,2))
GO

--Cadastros Tabela Categoria
INSERT INTO CATEGORIA VALUES (1,'DOCE')
INSERT INTO CATEGORIA VALUES (2,'SALGADO')
INSERT INTO CATEGORIA VALUES (3,'BEBIDA')
INSERT INTO CATEGORIA VALUES (4,'LIMPEZA')
INSERT INTO CATEGORIA VALUES (5,'CONGELADOS')
INSERT INTO CATEGORIA VALUES (6,'LEGUMES')
GO

--Cadastros Tabela Fornecedor
INSERT INTO FORNECEDOR VALUES ('FRUTIQUELLO')
INSERT INTO FORNECEDOR VALUES ('KIBOM')
INSERT INTO FORNECEDOR VALUES ('SITE ANDER')

--Cadastros Tabela Produto
INSERT INTO PRODUTO VALUES ('REFRIGERANTE COCA COLA',3,1,15,2.50)
INSERT INTO PRODUTO VALUES ('SABONETE PROTEX',4,2,50,1.99)
INSERT INTO PRODUTO VALUES ('CHOCOLATE SHOT LACTA',1,1,10,5.89)
INSERT INTO PRODUTO VALUES ('BOLACHA',1,2,3.50,3)
INSERT INTO PRODUTO VALUES ('FRIGIDEIRA TRAMONTINA',NULL,2,3,15.60)
INSERT INTO PRODUTO VALUES ('FACA TRAMONTINA',NULL,1,5,35.00)
INSERT INTO PRODUTO VALUES ('JOGO DE PRATOS',NULL,1,1,155.00)
GO

--Exemplo Junção de Tabelas sem JOIN
select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA from PRODUTO ,CATEGORIA WHERE Produto.CODCATEGORIA = CATEGORIA.CODCATEGORIA

--EXEMPLO INNER JOIN
select CATEGORIA.CODCATEGORIA, CODPRODUTO, NOMEPRODUTO, VALORUNITARIO, NOMECATEGORIA from PRODUTO JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = Produto.CODCATEGORIA 

1 - Exibir:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
valorunitario	-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:
		
2 - Exibir:
NomeProduto		-> PRODUTO
NomeFornecedor	-> FORNECEDOR
Relacionamento entre PRODUTO E FORNECEDOR: CodFornecedor
--Código:

select NOMEPRODUTO, NOMEFORNECEDOR from PRODUTO JOIN FORNECEDOR ON FORNECEDOR.CODFORNECEDOR = PRODUTO.CODFORNECEDOR


--EXEMPLO LEFT JOIN
3 - Exibir:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:
select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA from PRODUTO LEFT JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA

--EXEMPLO RIGHT JOIN
4 - Exibir:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:

select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA from PRODUTO RIGHT JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA


--EXEMPLO FULL JOIN
5 - Exibir:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:

select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA from PRODUTO FULL JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA


--LEFT EXCLUDING JOIN (EXCLUIR A JUNÇÃO)
Exibir:
codproduto		-> PRODUTO
nomeproduto		-> PRODUTO
nomecategoria	-> CATEGORIA
--Código:

select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA from PRODUTO LEFT EXCLUDING JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA

--RIGHT EXCLUDING JOIN (EXCLUIR A JUNÇÃO)
--Código:
select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA from PRODUTO RIGHT EXCLUDING JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA
--FULL EXCLUDING JOIN (EXCLUIR A JUNÇÃO)
--Código:
select CODPRODUTO, NOMEPRODUTO, NOMECATEGORIA from PRODUTO FULL EXCLUDING JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA




--EXERCÍCIOS
Inner JOIN

Exibir os seguintes campos:
NomeProduto
NomeCategoria
Quantidade

Obs: Apenas dos produtos que forem da categoria: Doce

select NOMEPRODUTO, NOMECATEGORIA ,QUANTIDADE from PRODUTO JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA WHERE CATEGORIA.CODCATEGORIA = 1
---------------------------------------
Inner Join
Exibir os seguintes campos:
CodProduto
NomeProduto
NomeFornecedor

Obs: Apenas dos produtos que tiverem preço acima de 10.00

select CODPRODUTO , NOMEPRODUTO, NOMEFORNECEDOR from PRODUTO JOIN FORNECEDOR ON FORNECEDOR.CODFORNECEDOR = PRODUTO.CODFORNECEDOR WHERE VALORUNITARIO > 10.00
----------------------------------------

Inner Join
Exibir os seguintes campos:
NomeProduto
NomeCategoria
NomeFornecedor

select NOMEPRODUTO, NOMECATEGORIA, NOMEFORNECEDOR from PRODUTO JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA JOIN FORNECEDOR ON FORNECEDOR.CODFORNECEDOR = PRODUTO.CODFORNECEDOR
----------------------------------------------
Left Join
Exibir os seguintes campos: 
NomeProduto
NomeCategoria
Quantidade

OBS: Os produtos que tem ou não categorias vinculadas. 
Apenas produtos com quantidade acima de 5

select NOMEPRODUTO, NOMECATEGORIA, QUANTIDADE from PRODUTO LEFT JOIN CATEGORIA ON CATEGORIA.CODCATEGORIA = PRODUTO.CODCATEGORIA WHERE QUANTIDADE > 5
----------------------------------------------

Right Join
Exibir os seguintes campos:
NomeProduto
NomeFornecedor
Quantidade
Preco

Obs: Os produtos que tem ou não fornecedores vinculados

select  NOMEPRODUTO, NOMEFORNECEDOR, QUANTIDADE, VALORUNITARIO from PRODUTO RIGHT JOIN FORNECEDOR ON FORNECEDOR.CODFORNECEDOR = PRODUTO.CODFORNECEDOR

SELECT * FROM PRODUTO
